#configure system 
1 :
  expectedPage  : 'setupMenu'
  PageOptions : 
    1 : 
        expectedPage : 'sysconfig'
        PageOptions : '0'
        PageSettings : 
            step1 :
              1 : 'Enter your selection ['
              'wrongValue' : '3'
              'enter' : 'Enter your selection ['
            step2 :
              1 : 'Please confirm you want to proceed with the new configuration [N]:'
              'wrongValue' : '3'             
              'enter' : 'Please confirm you want to proceed with the new configuration [N]:'
            step3 : 
              'N' : 'EZ-EDGE Local Craft Interface - Configuration Parameters'
              'Y' : 'Changes applied successfully. Press any key to continue'
              'd' : 'Please confirm you want to proceed with the new configuration [N]:'
              'enter' : 'EZ-EDGE Local Craft Interface - Configuration Parameters'
    2 : 
        expectedPage : 'netConfig'
        PageOptions : '0'
        PageSettings : 
            step1 :
              '192.168.3.254' : 'EZ-EDGE Subnet mask ['
              'wrongValue' : '333.128.3.3'
              'enter' : 'EZ-EDGE Subnet mask ['
            step2 :
              '255.255.255.0' : 'EZ-EDGE Default Gateway ['
              'wrongValue' : '333.128.3.3'
              'enter' : 'EZ-EDGE Default Gateway ['
            step3 : 
              '192.168.3.1' : 'Please confirm you want to proceed with the new configuration [N]:'
              'wrongValue' : '333.128.3.3'
              'enter' : 'Please confirm you want to proceed with the new configuration [N]:'
            step4 : 
              'N' : 'Configuration Parameters'
              'Y' : 'Changes applied successfully. Press any key to continue'
              'd' : 'Please confirm you want to proceed with the new configuration [N]:'
              'enter' : 'EZ-EDGE Local Craft Interface - Configuration Parameters'
    3 : 
        expectedPage : 'timeConfig'
        PageOptions : '0'
        PageSettings : 
            step1 :
              '2015-10-12' : 'Current UTC Time (HH:MM:SS)  ['
              'wrongValue' : '2054-23-28'
              'enter' : 'Current UTC Time (HH:MM:SS)  ['
            step2 :
              '12:10:09' : Please confirm you want to proceed with the new configuration [N]:'
              'wrongValue' : '28:15:12'
              'enter' : Please confirm you want to proceed with the new configuration [N]:'
            step3 : 
              'N' : 'EZ-EDGE Local Craft Interface - Configuration Parameters'
              'Y' : 'Changes applied successfully. Press any key to continue'
              'd' : 'Please confirm you want to proceed with the new configuration [N]:'
              'enter' : 'EZ-EDGE Local Craft Interface - Configuration Parameters'